server:
  port: 8888
  session:
    timeout: 1800
  #address: acount.yayao8.com
  tomcat:
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60 
spring:
   datasource:
     name: master
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://120.77.253.90:3306/payment_system_db
     username: root
     password: liliu
   redis:
     host: 120.77.253.90
     password: liliu
     port: 6379 
     database: 1
     timeout: 3000
     pool: 
       min-idle: 100
       max-idle: 300
       max-active: 800 
myPugin: 
  session: 
    myDomainName: newzhuan.cn
  projectName: PaymentSystem
  location: /home/config/thirdParty.properties
  requestAuth: requestAuthProd
  sevenSecondsDomainUrl: http://www.newzhuan.cn
  bookStoreDomainUrl: http://book.newzhuan.cn
  alibaba:
    alipay:
      APP_ID: 2017081808253496 
      APP_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCnAu8NDakgD5RRtYl70Q5pz7k1QIQ2YL80yVBL5/ciwgjOYsV+GXq4hJkNOzIOZArblMZvSaGGAmugkBKVhdMiXhBkVxH6OAZayUPsve1dmjBi2K5NO8Qm34z3waml8F+lGWxw21GGQIUvxbZk1tv4Pb1fDDqOpOXNYseLmWLfw9mVZ217LOVlgVMVBJ/1CTkqDUO7hUzHYTT0h4BzpxvlQltq4TIX6rhBMrv6gai3BXQqy7tZRZh5pXkOZVMlCnYdxM2QLLKrtGSpcFP+HIGGH8Yy8T4dvuNTzzQRwjrKSu+EiyEtyfMfYtKLRHLWDGfvmr8/z/2RluBQsKEdmoTRAgMBAAECggEAPNWUvex77nG+VQULT06XMXO4wuz9O9GB1HiAByY3nzGOg5720Tf2u7+RAIDPeu52BgXrQh5P98Bp89KG8nAMuDgLQIF2yu4dYnRtiY6lJ7NCbL8AvqFGkeJcNuMUKJ2mOT1JgtJgn8ZgvUYHajPZbFMQ585MhikKjAWvKep1WYwkAnXnBpO1no1Tf2CvgEFbJzRpOKUyuBeWLXuf+kl3kPBQTiXsT5rza7SS6uvmEEceIyP0oiJU9+hiELfMnoSUj5fcdBrBfbUwMFso14noLmALCSDNz02jsXEQreSYlTMvl7Q1Vj8xUs4BZQQE4KRhEhjsoXPnqy+gGg8S5KwMAQKBgQD6xl28L/c/bOFR0Ebh+x2dti00iVvE5sccl8XlhJkhYSG8uU2gZvXxxM4i8ybmU4YBd/NWHGS9WDxY8Hj5b2wev4oX1h3sKNFMLw+NGcsuIOojDWAHSKejTZi5qsEE5KVA1d1KtDCZueUjcJ9iqs99wmQy8FKxyHSged9EwKEZXQKBgQCqfcX809hZP/iw1P8gdD+7RmkmDEJ1t/+Ev2V+N1xfH375/d0QxieH9XGnGpWZ77XbQOR+kQzgVvj5wa2UfoclDMQwc3XWCNIhrxqAV8NCUed3d3TUK/XCb68/u4m4XaDToJGO/B/JwtawnazZjlAdESNYNb8V6zNJWAcZPAq+BQKBgEM9FLz0j3KuGuv40EifMB2tTwmbGsP8rL5541Ha78QHayhS9wFfGeqtPigY0gFHu9KA+vnHuysZkXS3ZXhb672C1d/2RSeg+h1XMPBATj4cDStA1tKdJHWgxKZjpkVNmRF9RkxVbAKL2WhbNiEac2/gw0T1MvcALGUqyDaC/67xAoGADpbEomXeVYTL2xXe3wATlArqZH8YEMq16r4WCT7jgKBJVUsL56uNJm0yVIJJ2upQPXrIEqyG1YubsoOIPvS0y87T2vGGW9JVaNx7ABCCfOJVVDu8m4tHdGPqMyHxHv2kDXfn/LxGXBV4GZTkfZlX8aTNyXaP62g880G9GcOxh6ECgYEA1Eq8E9TtkjnW7iZbM+xtMiqCRn7a3Weghi81UjjafRrCRnzbgylagC2MQIyxKmv08MBs40Fwsa5870c4MBSsPWQum5QpUM5vrbY11iG8i2YHd3CZAj6GMUFJshjmOLm+27ORzgzhHzm0XxMrPonfNabGV8fKQkvziJ40OUwLRsc=
      APP_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApwLvDQ2pIA+UUbWJe9EOac+5NUCENmC/NMlQS+f3IsIIzmLFfhl6uISZDTsyDmQK25TGb0mhhgJroJASlYXTIl4QZFcR+jgGWslD7L3tXZowYtiuTTvEJt+M98GppfBfpRlscNtRhkCFL8W2ZNbb+D29Xww6jqTlzWLHi5li38PZlWdteyzlZYFTFQSf9Qk5Kg1Du4VMx2E09IeAc6cb5UJbauEyF+q4QTK7+oGotwV0Ksu7WUWYeaV5DmVTJQp2HcTNkCyyq7RkqXBT/hyBhh/GMvE+Hb7jU880EcI6ykrvhIshLcnzH2LSi0Ry1gxn75q/P8/9kZbgULChHZqE0QIDAQAB
      ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgLp4pohzptgY+59o11fAxeY5xwEMQPS5a0uauzRzHkAOjZR2nKx/V7uyZOYNCA+FQtKop+xabwMYs+0MsQubTc6C8E8viZ+o1Q3W0pKn6oYDh6rMqcYQGKEQ61NTgy/xAJUCbFgFM2lwrh4QfwtYGvuio2v8A7j3TN8szKErGwvrxAjAz26auuhSZfUqJgGqP++4ChzeHYnlJeoay7PXFfIOiL5Yl6HqgC0eVU36GGmvYY3rAJgbtnQvmVfQxAzD6JhFMkhYFj1wwFtFYr5s+pF1igZSs4VlftsMfVCBpsojQXddgqF6OL2d63ZfMi2OXfFriUf7nG3BpXhF+kag1wIDAQAB
  weixin: 
    weChatPayment: 
      APPID: wx9916b928e1ae2ccb
      SECRET: 99cfd6e70e1333472989dd9f45fca83c
      MCH_ID: 1489128222
      API: abb763888198076d2a4ab3a10cf0cee3
  rabbitmq:
    PAYMENTREDIRECT_DIRECT_EXCHANGE: paymentredirect.bookstore.exchange.direct
    PAYMENTREDIRECT_DIRECT_ROUTINGKEY: paymentredirect.bookstore.routingkey.direct
    PAYMENTREDIRECT_DIRECT_QUEUE: paymentredirect.bookstore.queue.direct